version: 2

models:
  - name: DimCustomer
    description: "Customer Dimension"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

sources:
  - name: tpch
    database: justin_kolpak  
    schema: tpch
    tables:
      - name: silver_customer
      - name: silver_nation
      - name: silver_region